export const events = [
    {
        id: 1,
        eventName: '"GIFTS OF THE PASSING AUTUMN" ACRYLIC WORKSHOP',
        startDate: null,
        date: '2025-11-05',
        time: '6:00 pm - 9:00 pm',
        day: null,
        price: 78,
        selected: false,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly. All supplies provided + snacks and beverages',
        img: 'grapes.PNG',
        modalDescription: 'An atmospheric workshop where participants paint a luscious grape cluster, learning to capture volume, light, and texture in a painterly style.',
        modalIncludes: null,
        modalDiscount: null,
    },
    {
        id: 2,
        eventName: '"FOLLOW THE LIGHT" ACRYLIC CLASS',
        startDate: null,
        date: '2025-11-07',
        time: '6:00 pm - 9:00 pm',
        day: null,
        price: 78,
        selected: false,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly. All supplies provided + snacks and beverages',
        img: 'down.PNG',
        modalDescription: 'An inspiring acrylic workshop where you’ll paint a glowing lighthouse and ocean waves, exploring light, texture, and atmosphere.',
        modalIncludes: null,
        modalDiscount: null,
    },
    {
        id: 3,
        eventName: '"STOP FOR A MOMENT" ACRYLIC WORKSHOP',
        startDate: null,
        date: '2025-11-12',
        time: '6:00 pm - 9:00 pm',
        day: null,
        price: 78,
        selected: false,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly. All supplies provided + snacks and beverages',
        img: 'violet.PNG',
        modalDescription: 'A relaxing acrylic workshop where you’ll capture the calm beauty of sunset and wildflowers with soft tones and gentle brushstrokes.',
        modalIncludes: null,
        modalDiscount: null,
    },
    {
        id: 4,
        eventName: ' "DELICATE AZURE" ACRYLIC CLASS',
        startDate: null,
        date: '2025-10-17',
        time: '6:00 pm - 9:00 pm',
        day: null,
        price: 78,
        selected: false,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly. All supplies provided + snacks and beverages',
        img: 'AZUR.PNG',
        modalDescription: 'In this acrylic class, we’ll paint a delicate still life with vibrant blue cornflowers in vintage jugs — a bright and elegant artwork for any interior.',
        modalIncludes: null,
        modalDiscount: null,
    },
    {
        id: 5,
        eventName: ' "FALL’S LAST PALETTE" ACRYLIC CLASS',
        startDate: null,
        date: '2025-10-22',
        time: '6:00 pm - 9:00 pm',
        day: null,
        price: 78,
        selected: false,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly. All supplies provided + snacks and beverages',
        img: 'PALETTE.PNG',
        modalDescription: 'Step by step, we’ll paint a misty forest path framed with vibrant fall foliage — a perfect blend of depth, texture, and atmosphere.',
        modalIncludes: null,
        modalDiscount: null,
    },
    {
        id: 6,
        eventName: 'ABSTRACT ACRYLIC CITYSCAPE',
        startDate: null,
        date: '2025-10-24',
        time: '6:00 pm - 9:00 pm',
        day: null,
        price: 78,
        selected: false,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'NO MORE SPOTS AVAILABLE',
        img: 'CALGARY.PNG',
        modalDescription: 'Discover the power of abstract palette knife painting in this workshop, where we capture Calgary’s skyline in bold textures and glowing contrasts.',
        modalIncludes: null,
        modalDiscount: null,
    },
    {
        id: 7,
        eventName: 'FLIGHT THROUGH TIME',
        startDate: null,
        date: '2025-11-14',
        time: '6:00 pm - 9:00 pm',
        day: null,
        price: 78,
        selected: false,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly. All supplies provided + snacks and beverages',
        img: 'crown.PNG',
        modalDescription: 'An expressive acrylic workshop where you’ll paint a majestic raven against warm autumn tones, exploring contrast, texture, and mood.',
        modalIncludes: null,
        modalDiscount: null,
    },
    {
        id: 8,
        eventName: 'WALERCOLOR ATHABASCA FALLS',
        startDate: null,
        date: '2025-10-29',
        time: '6:00 pm - 9:00 pm',
        day: null,
        price: 78,
        selected: false,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly. All supplies provided + snacks and beverages',
        img: 'ATHABASKA.PNG',
        modalDescription: 'In this watercolor workshop, we will capture the majestic beauty of Athabasca Falls surrounded by the Rocky Mountains. Step by step, you’ll learn how to paint flowing water, misty spray, and textured rocks while exploring the unique transparency and softness of watercolor.',
        modalIncludes: null,
        modalDiscount: null,
    },
    {
        id: 9,
        eventName: '"MONOCHROME" ACRYLIC WORKSHOP',
        startDate: null,
        date: '2025-11-19',
        time: '6:00 pm - 9:00 pm',
        day: null,
        price: 78,
        selected: false,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly. All supplies provided + snacks and beverages',
        img: 'mono.PNG',
        modalDescription: 'An atmospheric acrylic workshop where you’ll paint majestic peaks and autumn slopes, learning to convey depth, light, and natural harmony.',
        modalIncludes: null,
        modalDiscount: null,
    },
    {
        id: 10,
        eventName: 'BOUQUET OF MEMORIES',
        startDate: null,
        date: '2025-11-21',
        time: '6:00 pm - 9:00 pm',
        day: null,
        price: 78,
        selected: false,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly. All supplies provided + snacks and beverages',
        img: 'boucet.PNG',
        modalDescription: 'A cozy acrylic workshop where you’ll paint an autumn still life by the window, capturing warmth, nostalgia, and the poetry of fading leaves.',
        modalIncludes: null,
        modalDiscount: null,
    },
    {
        id: 11,
        eventName: '"TRUE ILLUSION" ACRYLIC LANDSCAPE',
        startDate: null,
        date: '2025-11-26',
        time: '6:00 pm - 9:00 pm',
        day: null,
        price: 78,
        selected: false,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly. All supplies provided + snacks and beverages',
        img: 'aurora.PNG',
        modalDescription: 'An enchanting acrylic workshop where you’ll paint a cozy cabin under the northern lights, exploring light, texture, and the magic of winter night skies.',
        modalIncludes: null,
        modalDiscount: null,
    },
    {
        id: 12,
        eventName: 'WAITING FOR A MIRACLE',
        startDate: null,
        date: '2025-11-28',
        time: '6:00 pm - 9:00 pm',
        day: null,
        price: 78,
        selected: false,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly. All supplies provided + snacks and beverages',
        img: 'light.PNG',
        modalDescription: 'A heartwarming acrylic workshop where you’ll paint a glowing candle surrounded by evergreens, capturing the quiet magic and warmth of winter evenings.',
        modalIncludes: null,
        modalDiscount: null,
    },
    {
        id: 13,
        eventName: 'CHRISTMAS ORNAMENT PAINTING WORKSHOP',
        startDate: null,
        date: '2025-12-14',
        time: '2:00 pm - 5:00 pm',
        day: null,
        price: 78,
        selected: false,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly. All supplies provided + snacks and beverages',
        img: 'IMG_8403.JPG',
        modalDescription: 'Join our Christmas Ornament Painting Workshop and design your own festive ornaments — perfect for your Christmas tree or as handmade gifts filled with warmth and love.',
        modalIncludes: null,
        modalDiscount: null,
    },
    {
        id: 14,
        eventName: 'CHRISTMAS ORNAMENT PAINTING WORKSHOP',
        startDate: null,
        date: '2025-12-21',
        time: '2:00 pm - 5:00 pm',
        day: null,
        price: 78,
        selected: false,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly. All supplies provided + snacks and beverages',
        img: 'IMG_8403.JPG',
        modalDescription: 'Join our Christmas Ornament Painting Workshop and design your own festive ornaments — perfect for your Christmas tree or as handmade gifts filled with warmth and love.',
        modalIncludes: null,
        modalDiscount: null,
    },
    {
        id: 15,
        eventName: 'ACRYLIC PAINTING COURSE "REALISTIC FLOWERS" (5 sessions)',
        startDate: 'November 03 -',
        date: '2025-12-01',
        time: '05:00 pm - 08:00 pm',
        day: "Mondays, ",
        price: 315,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly. All supplies provided + snacks and beverages',
        img: 'IMG_8470.JPG',
        modalDescription: 'Discover the magic of floral painting in our beginner-friendly acrylic course.' +
            '<div class="modal-body-description-bold">\n' +
            '                                Step by step, you’ll learn how to create soft petals, rich colors, and lifelike depth — even if you’ve never held a brush before. No experience needed — just curiosity and creativity. Let’s bring flowers to life on canvas.\n' ,
        modalIncludes: null,
        modalDiscount: null,
    },
    {
        id: 14,
        eventName: 'ACRYLIC PAINTING COURSE "TEXTURES AROUND US" (5 sessions)',
        startDate: 'June 14 -',
        date: '2025-07-12',
        time: '03:00 pm - 06:00 pm',
        day: "Saturdays, ",
        price: 315,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly. All supplies provided + snacks and beverages',
        img: 'Acrylic painting course.jpg',
        modalDescription: 'Learn techniques to create natural textures, from the softness of clouds to the roughness of a rocky mountain.' +
            '<div class="modal-body-description-bold">\n' +
            '                                In this course you will learn:how to convey the depth and texture of water, clouds, mountains, and various trees; special techniques of working with acrylic paints; painting using various tools to create realistic natural images.\n' ,
        modalIncludes: null,
        modalDiscount: null,
    },
];

export const infinityEvent = [
    {
        id: 1,
        eventName: 'REGULAR ART CLASSES FOR ADULTS (4 classes)',
        time: '3:00 pm - 6:00 pm',
        date: '%',
        day: 'Saturday',
        price: 180,
        selected: false,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'All supplies provided',
        img: 'photo.webp',
        modalDescription: "Master visual arts through group lessons designed to your interests and skill level. Explore painting, drawing, and composition at your own pace in a relaxed and supportive environment. ",
        modalIncludes: null,
        modalDiscount: "for four classes"
    },
    {
        id: 2,
        eventName: 'PRIVATE ART CLASSESES',
        time: '-',
        date: '%',
        day: 'Monday - Friday',
        price: 75,
        selected: false,
        location: 'IN ART Studio, 1324 11 Ave SW, #202, Calgary',
        description: 'All supplies provided',
        img: 'adults.JPG',
        modalDescription: "Creativity, dreams, inspiration - the world of art awaits you! We practice a variety of techniques, materials and subjects in our classes. ",
        modalIncludes: null,
        modalDiscount: "for 1 hour"
    },
]
