export const events = [
    {
        id: 1,
        eventName: 'WINTER WARMTH ACRYLIC CLASS',
        startDate: null,
        date: '2025-12-05',
        time: '6:00 pm - 9:00 pm',
        day: null,
        price: 78,
        selected: false,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly. All supplies provided + snacks and beverages',
        img: 'IMG_8477.PNG',
        modalDescription: 'Join us for a cozy acrylic workshop and capture the heartwarming scene — a red mitten holding pinecones amid softly falling snow.',
        modalIncludes: null,
        modalDiscount: null,
    },
    {
        id: 2,
        eventName: 'GIFTS ON THE WAY WATERCOLOR CLASS',
        startDate: null,
        date: '2025-12-10',
        time: '6:00 pm - 9:00 pm',
        day: null,
        price: 78,
        selected: false,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly. All supplies provided + snacks and beverages',
        img: 'IMG_9173.PNG',
        modalDescription: 'Let’s capture the cozy spirit of the holidays in watercolor — a charming red car bringing gifts through the snowy streets.',
        modalIncludes: null,
        modalDiscount: null,
    },
    {
        id: 3,
        eventName: 'WINTER CHARM ACRYLIC CLASS',
        startDate: null,
        date: '2025-12-17',
        time: '6:00 pm - 9:00 pm',
        day: null,
        price: 78,
        selected: false,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly. All supplies provided + snacks and beverages',
        img: 'IMG_0011.PNG',
        modalDescription: 'Create your own Christmas magic! In this cozy art session, you’ll paint a beautiful landscape using acrylics.',
        modalIncludes: null,
        modalDiscount: null,
    },
    {
        id: 4,
        eventName: '"TRUE ILLUSION" ACRYLIC LANDSCAPE',
        startDate: null,
        date: '2025-11-26',
        time: '6:00 pm - 9:00 pm',
        day: null,
        price: 78,
        selected: false,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly. All supplies provided + snacks and beverages',
        img: 'aurora.PNG',
        modalDescription: 'An enchanting acrylic workshop where you’ll paint a cozy cabin under the northern lights, exploring light, texture, and the magic of winter night skies.',
        modalIncludes: null,
        modalDiscount: null,
    },
    {
        id: 5,
        eventName: 'WAITING FOR A MIRACLE',
        startDate: null,
        date: '2025-11-28',
        time: '6:00 pm - 9:00 pm',
        day: null,
        price: 78,
        selected: false,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly. All supplies provided + snacks and beverages',
        img: 'light.PNG',
        modalDescription: 'A heartwarming acrylic workshop where you’ll paint a glowing candle surrounded by evergreens, capturing the quiet magic and warmth of winter evenings.',
        modalIncludes: null,
        modalDiscount: null,
    },
    {
        id: 6,
        eventName: 'CHRISTMAS ORNAMENT PAINTING WORKSHOP',
        startDate: null,
        date: '2025-12-21',
        time: '2:00 pm - 5:00 pm',
        day: null,
        price: 78,
        selected: false,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly. All supplies provided + snacks and beverages',
        img: 'IMG_9399.JPG',
        modalDescription: 'Join our Christmas Ornament Painting Workshop and design your own festive ornaments — perfect for your Christmas tree or as handmade gifts filled with warmth and love.',
        modalIncludes: null,
        modalDiscount: null,
    },
    {
        id: 7,
        eventName: 'ACRYLIC PAINTING COURSE "REALISTIC FLOWERS" (5 sessions)',
        startDate: 'November 03 -',
        date: '2025-11-03',
        time: '05:00 pm - 08:00 pm',
        day: "Mondays, ",
        price: 315,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly. All supplies provided + snacks and beverages',
        img: 'IMG_8470.JPG',
        modalDescription: 'Discover the magic of floral painting in our beginner-friendly acrylic course.' +
            '<div class="modal-body-description-bold">\n' +
            '                                Step by step, you’ll learn how to create soft petals, rich colors, and lifelike depth — even if you’ve never held a brush before. No experience needed — just curiosity and creativity. Let’s bring flowers to life on canvas.\n' ,
        modalIncludes: null,
        modalDiscount: null,
    },
    {
        id: 8,
        eventName: 'WATERCOLOR POSTCARDS WORKSHOP',
        startDate: null,
        date: '2025-12-19',
        time: '6:00 pm - 9:00 pm',
        day: null,
        price: 78,
        selected: false,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly. All supplies provided + snacks and beverages',
        img: 'IMG_0124.JPG',
        modalDescription: 'Create your own set of delicate watercolor postcards — from cozy seasonal scenes to floral miniatures. We’ll explore simple techniques like gentle washes, layering, and subtle line accents, making the process comfortable even for beginners.',
        modalIncludes: null,
        modalDiscount: null,
    },
];

export const infinityEvent = [
    {
        id: 1,
        eventName: 'REGULAR ART CLASSES FOR ADULTS (4 classes)',
        time: '3:00 pm - 6:00 pm',
        date: '%',
        day: 'Saturday',
        price: 180,
        selected: false,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'All supplies provided',
        img: 'photo.webp',
        modalDescription: "Master visual arts through group lessons designed to your interests and skill level. Explore painting, drawing, and composition at your own pace in a relaxed and supportive environment. ",
        modalIncludes: null,
        modalDiscount: "for four classes"
    },
    {
        id: 2,
        eventName: 'PRIVATE ART CLASSESES',
        time: '-',
        date: '%',
        day: 'Monday - Friday',
        price: 75,
        selected: false,
        location: 'IN ART Studio, 1324 11 Ave SW, #202, Calgary',
        description: 'All supplies provided',
        img: 'adults.JPG',
        modalDescription: "Creativity, dreams, inspiration - the world of art awaits you! We practice a variety of techniques, materials and subjects in our classes. ",
        modalIncludes: null,
        modalDiscount: "for 1 hour"
    },
]
