export const events = [
    {
        id: 1,
        eventName: 'ACRYLIC PAINTING COURSE "REALISTIC FLOWERS" (5 sessions)',
        startDate: 'June 19 -',
        date: '2025-07-17',
        time: '06:00 pm - 09:00 pm',
        day: "Wednesdays, ",
        price: 315,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly. All supplies provided + snacks and beverages',
        img: 'flower.webp',
        modalDescription: 'Discover the magic of floral painting in our beginner-friendly acrylic course.' +
            '<div class="modal-body-description-bold">\n' +
            '                                Step by step, you’ll learn how to create soft petals, rich colors, and lifelike depth — even if you’ve never held a brush before. No experience needed — just curiosity and creativity. Let’s bring flowers to life on canvas.\n' ,
        modalIncludes: null,
        modalDiscount: null,
    },
    {
        id: 2,
        eventName: 'WILD WEST IN WATERCOLOR',
        startDate: null,
        date: '2025-07-02',
        time: '6:00 pm - 9:00 pm',
        day: null,
        price: 78,
        selected: false,
        location: 'IN ART Studio, 1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly. All supplies provided + snacks and beverages',
        img: 'hat.PNG',
        modalDescription: 'A light and inspiring session for those who dream of the Stampede and the scent of the prairies. We’ll paint a stylish cowboy hat using soft watercolor layers, learning to capture texture, light, and the spirit of the Wild West.',
        modalIncludes: null,
        modalDiscount: null,
    },
    {
        id: 3,
        eventName: 'COWGIRL IN BLOOM ACRYLIC CLASS',
        startDate: null,
        date: '2025-07-06',
        time: '11:00 am - 2:00 pm',
        day: null,
        price: 73.5,
        selected: false,
        location: 'IN ART Studio, 1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly. All supplies provided + snacks and beverages',
        img: 'legs.PNG',
        modalDescription: 'Bold boots, blooming flowers, and the spirit of the wild. In this acrylic painting class, we’ll capture a playful cowgirl vibe through expressive brushstrokes and vibrant textures. Perfect for beginners and free spirits — come paint a little piece of western charm with us!',
        modalIncludes: null,
        modalDiscount: null,
    },
    {
        id: 4,
        eventName: '"EIFFEL VIEW" ACRYLIC PAINTING CLASS',
        startDate: null,
        date: '2025-07-09',
        time: '06:00 pm - 09:00 pm',
        day: null,
        price: 73.5,
        selected: false,
        location: 'IN ART Studio, 1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly. All supplies provided + snacks and beverages',
        img: 'paris.PNG',
        modalDescription: 'Let’s bring a little Parisian romance to the canvas! In this class, we’ll paint a cozy window view of the Eiffel Tower using layered acrylic techniques. Soft curtains, flower pots, and warm light will set the mood as we explore perspective, atmosphere, and charming detail — perfect for all levels.',
        modalIncludes: null,
        modalDiscount: null,
    },
    {
        id: 5,
        eventName: 'SICILIAN LIGHT WATERCOLOR CLASS',
        startDate: null,
        date: '2025-07-11',
        time: '6:00 pm - 9:00 pm',
        day: null,
        price: 78,
        selected: false,
        location: 'IN ART Studio, 1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly. All supplies provided + snacks and beverages',
        img: 'lemons.PNG',
        modalDescription: 'Sun-drenched hills, sea breeze, and golden lemons — this class is a journey to Sicily through watercolor. We’ll capture the charm of Mediterranean landscapes and the freshness of citrus branches using loose washes, vibrant color, and delicate details. A perfect escape for your brush and soul.',
        modalIncludes: null,
        modalDiscount: null,
    },
    {
        id: 6,
        eventName: 'ROAD TRIP VIBES ACRYLIC CLASS',
        startDate: null,
        date: '2025-07-16',
        time: '6:00 pm - 9:00 pm',
        day: null,
        price: 73.5,
        selected: false,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly. All supplies provided + snacks and beverages',
        img: 'trip.PNG',
        modalDescription: 'Grab your imagination and hit the road! In this acrylic painting class, we will paint a fun vintage minivan against a dreamy landscape of sunset, mountains, and hot air balloons. Learn how to apply bold colors, create texture, and convey a carefree spirit of adventure. Perfect for all levels and hearts full of wanderlust.',
        modalIncludes: null,
        modalDiscount: null,
    },
     {
        id: 7,
        eventName: 'HUMMINGBIRD WATERCOLOR CLASS',
        startDate: null,
        date: '2025-07-18',
        time: '6:00 pm - 9:00 pm',
        day: null,
        price: 78,
        selected: false,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly. All supplies provided + snacks and beverages',
        img: 'bird.JPG',
        modalDescription: 'Delicate, vibrant, and full of motion — this class brings to life the charm of a hummingbird dancing among flowers. We’ll explore soft washes, fluid lines, and layering techniques to create a light, airy composition filled with color and grace. A perfect subject to celebrate the beauty of nature in watercolor.',
        modalIncludes: null,
        modalDiscount: null,
    },
    {
        id: 8,
        eventName: 'JUICY SUMMER ACRYLIC CLASS',
        startDate: null,
        date: '2025-07-23',
        time: '6:00 pm - 9:00 pm',
        day: null,
        price: 73.5,
        selected: false,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly. All supplies provided + snacks and beverages',
        img: 'watermelon.PNG',
        modalDescription: 'Bold colors, playful shapes, and the sweet taste of summer! In this class we will paint bright, juicy watermelons using expressive acrylic strokes and layering techniques. Perfect for beginners and anyone who craves summer freshness on canvas - capture the fun of the season together!',
        modalIncludes: null,
        modalDiscount: null,
    },
    {
        id: 9,
        eventName: 'POSTCARD FROM EUROPE',
        startDate: null,
        date: '2025-07-25',
        time: '6:00 pm - 9:00 pm',
        day: null,
        price: 78,
        selected: false,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly. All supplies provided + snacks and beverages',
        img: 'bicycle.PNG',
        modalDescription: 'Charming streets, blooming baskets, and that timeless European flair. In this watercolor class, we will paint a vintage bicycle surrounded by flowers — a soft, dreamy scene filled with color and light. Learn to work with gentle washes, layering, and detail to create a romantic moment on paper. Perfect for all skill levels.',
        modalIncludes: null,
        modalDiscount: null,
    },
    {
        id: 10,
        eventName: 'RUSTIC GRACE',
        startDate: null,
        date: '2025-07-30',
        time: '6:00 pm - 8:00 pm',
        day: null,
        price: 73.5,
        selected: false,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly. All supplies provided + snacks and beverages',
        img: 'vase.PNG',
        modalDescription: 'A tender bouquet with a rustic twist — in this acrylic painting class, we will create a charming still life featuring soft, delicate roses arranged in a vintage watering can. Learn how to build floral form, play with gentle color transitions, and add texture for a romantic, country-style composition. Perfect for all skill levels and flower lovers!',
        modalIncludes: null,
        modalDiscount: null,
    },
    {
        id: 11,
        eventName: '“IRISES” TEXTURE PASTE CLASS',
        startDate: null,
        date: '2025-06-11',
        time: '6:00 pm - 9:00 pm',
        day: null,
        price: 73.5,
        selected: false,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly. All supplies provided + snacks and beverages',
        img: 'irises.webp',
        modalDescription: 'Learn the basics of textured painting, how to use a palette knife, and how to create expressive floral shapes',
        modalIncludes: null,
        modalDiscount: null,
    },
     {
        id: 12,
        eventName: 'DOWNTOWN ACRYLIC CLASS”',
        startDate: null,
        date: '2025-06-18',
        time: '6:00 pm - 9:00 pm',
        day: null,
        price: 73.5,
        selected: false,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly. All supplies provided + snacks and beverages',
        img: 'сity.webp',
        modalDescription: 'Capture the energy and charm of Calgary’s skyline in this step-by-step acrylic painting workshop',
        modalIncludes: null,
        modalDiscount: null,
    },
    {
        id: 13,
        eventName: 'SILENT FAREWELL LANDSCAPE',
        startDate: null,
        date: '2025-06-20',
        time: '6:00 pm - 9:00 pm',
        day: null,
        price: 73.5,
        selected: false,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly. All supplies provided + snacks and beverages',
        img: 'buy.webp',
        modalDescription: 'Learn how to build depth with light and shadow, and create a peaceful composition — step by step, even without experience.',
        modalIncludes: null,
        modalDiscount: null,
    },
    {
        id: 14,
        eventName: 'PEONIES IN BLOOM PAINTING',
        startDate: null,
        date: '2025-06-25',
        time: '6:00 pm - 9:00 pm',
        day: null,
        price: 73.5,
        selected: false,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly. All supplies provided + snacks and beverages',
        img: 'peonies.webp',
        modalDescription: 'Join us for a creative workshop where you’ll paint a delicate peony in rich acrylics.',
        modalIncludes: null,
        modalDiscount: null,
    },
    {
        id: 15,
        eventName: 'KISS OF THE TIDE SEASCAPE',
        startDate: null,
        date: '2025-06-27',
        time: '6:00 pm - 9:00 pm',
        day: null,
        price: 73.5,
        selected: false,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly. All supplies provided + snacks and beverages',
        img: 'sea.webp',
        modalDescription: 'Create a peaceful seascape featuring a boat, soft waves, and the warm glow of sunset.',
        modalIncludes: null,
        modalDiscount: null,
    },
    {
        id: 16,
        eventName: 'ACRYLIC PAINTING COURSE "REALISTIC FLOWERS" (5 sessions)',
        startDate: 'July 31 -',
        date: '2025-08-28',
        time: '03:00 pm - 06:00 pm',
        day: "Thursdays, ",
        price: 315,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly. All supplies provided + snacks and beverages',
        img: 'flower.webp',
        modalDescription: 'Discover the magic of floral painting in our beginner-friendly acrylic course.' +
            '<div class="modal-body-description-bold">\n' +
            '                                Step by step, you’ll learn how to create soft petals, rich colors, and lifelike depth — even if you’ve never held a brush before. No experience needed — just curiosity and creativity. Let’s bring flowers to life on canvas.\n' ,
        modalIncludes: null,
        modalDiscount: null,
    },
    {
        id: 17,
        eventName: 'ACRYLIC PAINTING COURSE "TEXTURES AROUND US" (5 sessions)',
        startDate: 'June 14 -',
        date: '2025-07-12',
        time: '03:00 pm - 06:00 pm',
        day: "Saturdays, ",
        price: 315,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly. All supplies provided + snacks and beverages',
        img: 'Acrylic painting course.jpg',
        modalDescription: 'Learn techniques to create natural textures, from the softness of clouds to the roughness of a rocky mountain.' +
            '<div class="modal-body-description-bold">\n' +
            '                                In this course you will learn:how to convey the depth and texture of water, clouds, mountains, and various trees; special techniques of working with acrylic paints; painting using various tools to create realistic natural images.\n' ,
        modalIncludes: null,
        modalDiscount: null,
    },
];

export const infinityEvent = [
    {
        id: 1,
        eventName: 'PRIVATE ART CLASSES FOR ADULTS',
        time: '3:00 pm - 5:00 pm',
        date: '%',
        day: 'Monday - Saturday',
        price: 150,
        selected: false,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'All supplies provided',
        img: 'photo.webp',
        modalDescription: "Master visual arts through personalized lessons designed to your interests and skill level. Explore painting, drawing, and composition at your own pace in a relaxed and supportive environment. ",
        modalIncludes: null,
        modalDiscount: "for one class"
    },
    {
        id: 2,
        eventName: 'REGULAR ART CLASSES FOR KIDS 4-6 YEARS OLD',
        time: '3:00 pm - 4:00 pm',
        date: '%',
        day: 'Friday',
        price: 30,
        selected: false,
        location: 'IN ART Studio, 1324 11 Ave SW, #202, Calgary',
        description: 'All supplies provided',
        img: '4-6.webp',
        modalDescription: "Creativity, dreams, inspiration - the world of art awaits your child! We practice a variety of techniques, materials and subjects in our regular kids classes. ",
        modalIncludes: null,
        modalDiscount: "for one class ( there is a discount if you book 4 classes )"
    },
]
